In [1]:
import numpy as npy

In [3]:
npy.arange(2, 50, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [5]:
l=[]
for i in range(5):
    l.append(float(input("Enter the numbers")))
print(l)
ar=npy.array(l)
print(ar)
print(type(ar))
l1=[]
for i in range(5):
    l1.append(float(input("Enter the numbers")))
print(l1)
ar1=npy.array(l1)
print(ar1)
print(type(ar1))
print(npy.concatenate((ar,ar1)))
print(npy.sort((npy.concatenate((ar,ar1)))))

Enter the numbers1
Enter the numbers2
Enter the numbers3
Enter the numbers4
Enter the numbers5
[1.0, 2.0, 3.0, 4.0, 5.0]
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
Enter the numbers6
Enter the numbers7
Enter the numbers8
Enter the numbers9
Enter the numbers10
[6.0, 7.0, 8.0, 9.0, 10.0]
[ 6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
ar=npy.array([[[0,1,2,3],
             [4,5,6,7]],
            [[0,1,2,3],
             [4,5,6,7]],
             [[0,1,2,3],
              [4,5,6,7]]])
print(ar.ndim)
print(ar.size)

3
24


In [8]:
a=npy.array([1,2,3,4,5,6])
print(a)
print(a.shape)
a1=a[npy.newaxis, :]
print(a1)
print(a1.shape)
a2=npy.expand_dims(a,axis=0)
print(a2)
print(a2.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1 2 3 4 5 6]]
(1, 6)


In [9]:
a=npy.array([[1,1],
             [2,2]])
a1=npy.array([[3,3],
              [4,4]])
print(a)
print(a1)
print(npy.vstack((a,a1)))
print(npy.hstack((a,a1)))

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [11]:
a=npy.array([11,11,12,13,14,15,15,16,17,18,11,12,13,14])
print(a)
print(npy.unique(a))
u,o=npy.unique(a,return_counts=True)
print(o)

[11 11 12 13 14 15 15 16 17 18 11 12 13 14]
[11 12 13 14 15 16 17 18]
[3 2 2 2 2 1 1 1]
